'use client';

import { Sparkles } from 'lucide-react';

interface ShapExplanationItem {
  feature: string;
  impact: number;
  direction: 'higher' | 'lower';
  description: string;
}

interface ShapExplanationsCardProps {
  explanations: ShapExplanationItem[];
}

/**
 * ShapExplanationsCard displays the game-theoretic carbon attribution breakdown details
 * generated by the SHAP math engine relative to baseline regional parameters.
 */
export function ShapExplanationsCard({ explanations }: ShapExplanationsCardProps) {
  return (
    <section className="bg-zinc-900 border border-zinc-800/80 p-6 rounded-2xl space-y-6">
      <div>
        <div className="flex items-center gap-2 text-emerald-500">
          <Sparkles className="w-5 h-5 animate-pulse" />
          <h2 className="text-lg font-bold">SHAP Advanced Carbon Explanations</h2>
        </div>
        <p className="text-xs text-zinc-500 dark:text-zinc-400 mt-1 font-semibold uppercase tracking-wider">
          Powered by Google Vertex AI Custom Explainer
        </p>
      </div>

      <div className="space-y-4">
        {explanations.map((exp) => (
          <div key={exp.feature} className="space-y-2 border-b border-zinc-800/50 pb-4 last:border-b-0 last:pb-0">
            <div className="flex justify-between items-center text-sm font-semibold">
              <span className="text-zinc-300">{exp.feature}</span>
              <span className={exp.direction === 'higher' ? 'text-amber-500' : 'text-emerald-500'}>
                {exp.direction === 'higher' ? '+' : '-'}{exp.impact}% relative impact
              </span>
            </div>
            <div className="w-full h-2 bg-zinc-950 rounded-full overflow-hidden">
              <div 
                className={`h-full rounded-full transition-all duration-300 ${exp.direction === 'higher' ? 'bg-amber-500' : 'bg-emerald-500'}`}
                style={{ width: `${exp.impact}%` }}
              ></div>
            </div>
            <p className="text-xs text-zinc-500 dark:text-zinc-400 leading-relaxed font-medium">
              {exp.description}
            </p>
          </div>
        ))}
      </div>
    </section>
  );
}
